name: project_zhihui
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - mysql-connector-python
  - redis-py
  - pillow
  - numpy
  - pandas
  - matplotlib
  - pip:
    - Django==5.1.7
    - djangorestframework==3.15.2
    - djangorestframework-simplejwt==5.5.0
    - django-cors-headers==4.7.0
    - mysqlclient==2.2.7
    - django-redis==5.4.0
    - redis==5.2.1
    - celery==5.5.1
    - python-dotenv==1.0.1
    - argon2-cffi==23.1.0
    - pytz==2025.1
    - pytest==8.3.5
    - pytest-cov==6.1.1
    - bandit==1.8.3
    - colorama==0.4.6
    - requests==2.32.3
    - openpyxl==3.1.5
    - gunicorn==23.0.0